import { Workout } from '../../core/models/workout';

export const demoWorkouts: Workout[] = [
  {
    id: 'quick-timer',
    title: 'Quick Timer',
    description: '30-second single burst timer with a 5-second prepare phase.',
    type: 'SIMPLE',
    prepareDurationSec: 5,
    rounds: 1,
    restBetweenRoundsSec: 0,
    exercises: [
      {
        id: 'ex-quick-1',
        name: 'Workout',
        sets: 1,
        workDurationSec: 30,
        restBetweenSetsSec: 0,
        restAfterExerciseSec: 0,
      },
    ],
  },
  {
    id: 'boxing-rounds',
    title: 'Boxing',
    description: '3 rounds of 3 minutes shadow boxing with 1 minute rest between rounds.',
    type: 'ROUND',
    prepareDurationSec: 10,
    rounds: 3,
    restBetweenRoundsSec: 60,
    exercises: [
      {
        id: 'ex-boxing-1',
        name: 'Boxing Round',
        sets: 1,
        workDurationSec: 180,
        restBetweenSetsSec: 0,
        restAfterExerciseSec: 0,
      },
    ],
  },
  {
    id: 'hiit-circuit',
    title: 'HIIT Circuit',
    description: 'High intensity interval training with jumping jacks and mountain climbers.',
    type: 'CUSTOM',
    prepareDurationSec: 5,
    rounds: 1,
    restBetweenRoundsSec: 0,
    exercises: [
      {
        id: 'ex-hiit-1',
        name: 'Jumping Jacks',
        sets: 3,
        workDurationSec: 30,
        restBetweenSetsSec: 15,
        restAfterExerciseSec: 30,
      },
      {
        id: 'ex-hiit-2',
        name: 'Mountain Climbers',
        sets: 3,
        workDurationSec: 30,
        restBetweenSetsSec: 15,
        restAfterExerciseSec: 0,
      },
    ],
  },
  {
    id: 'strength-training',
    title: 'Strength Training',
    description: 'Full-body foundational strength: Push-ups, Shoulder Press, and Squats.',
    type: 'CUSTOM',
    prepareDurationSec: 5,
    rounds: 1,
    restBetweenRoundsSec: 0,
    exercises: [
      {
        id: 'ex-strength-1',
        name: 'Push-ups',
        sets: 3,
        workDurationSec: 40,
        restBetweenSetsSec: 30,
        restAfterExerciseSec: 60,
      },
      {
        id: 'ex-strength-2',
        name: 'Dumbbell Shoulder Press',
        sets: 3,
        workDurationSec: 45,
        restBetweenSetsSec: 30,
        restAfterExerciseSec: 60,
      },
      {
        id: 'ex-strength-3',
        name: 'Squats',
        sets: 3,
        workDurationSec: 45,
        restBetweenSetsSec: 30,
        restAfterExerciseSec: 0,
      },
    ],
  },
];
